# -*- coding: utf-8 -*-

# MainWindow implementation generated from reading ui file 'E:\工作目录\项目资料\代码\python\caseTrasfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QWidget
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from transfer import run
from on_main import run_t
from openpyxl import load_workbook
from my_thread import My_thread

class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 520)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 621, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(140, 40, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(320, 40, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 130, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 131, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 50, 151, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 40, 75, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(160, 120, 101, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(self.btn_scan_file)
        self.pushButton_7.clicked.connect(self.btn_scan_file)
        self.pushButton_2.clicked.connect(self.old_create_xml)
        self.pushButton_8.clicked.connect(self.new_create_xml)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "caseTransferTool"))
        self.label.setText(_translate("MainWindow", "请选择Excel表格路径"))
        self.pushButton.setText(_translate("MainWindow", "浏览"))
        self.pushButton_2.setText(_translate("MainWindow", "生成XML"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "旧用例模板转化成XML"))
        self.label_4.setText(_translate("MainWindow", "请选择Excel表格路径"))
        self.pushButton_7.setText(_translate("MainWindow", "浏览"))
        self.pushButton_8.setText(_translate("MainWindow", "生成XML"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "新用例模板转化成XML"))

    def btn_scan_file(self):
        # print("点击了呢")
        file_name, file_type = QFileDialog.getOpenFileName(self, '选择文件', '.', "All Files(*)")
        # print(file_name)
        sender = self.sender()
        if sender == self.pushButton:
            self.lineEdit.setText(file_name)
        elif sender == self.pushButton_7:
            self.lineEdit_4.setText(file_name)
    def old_create_xml(self):
        # print("点击了呢")
        self.pushButton_2.setEnabled(False)
        excel_path = self.lineEdit.text().strip()
        # print(excel_path)
        message = run(excel_path)
        QMessageBox.about(self, "消息提示", message)
        self.pushButton_2.setEnabled(True)
    
    def new_create_xml(self):
        # print("点击了呢")
        self.pushButton_2.setEnabled(False)
        excel_path = self.lineEdit_4.text().strip()
        wb = load_workbook(excel_path)
        message  = run_t(wb)
        QMessageBox.about(self, "消息提示", message)
        self.pushButton_2.setEnabled(True)
